#!/bin/bash
# Script to create database 'gabe' via phpMyAdmin URL

echo "=== Database Creation Script for 'gabe' ==="
echo ""
echo "Step 1: Open phpMyAdmin in browser"
echo "URL: http://localhost/phpmyadmin/"
echo ""
echo "Step 2: Login credentials:"
echo "Username: root"
echo "Password: (leave empty)"
echo ""
echo "Step 3: Import SQL file"
echo "Click on 'Import' tab"
echo "Choose file: /opt/lampp/htdocs/mono-v2/database/create_gabe_database.sql"
echo "Click 'Go' to execute"
echo ""
echo "Step 4: Verify database"
echo "Database 'gabe' should appear in the left panel"
echo ""
echo "Alternative: Manual SQL Execution"
echo "Copy and paste this SQL in phpMyAdmin SQL tab:"
echo ""
echo "CREATE DATABASE IF NOT EXISTS \`gabe\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo ""
echo "=== Quick Access Links ==="
echo "phpMyAdmin: http://localhost/phpmyadmin/"
echo "Application: http://localhost/mono-v2/"
echo ""
echo "=== File Location ==="
echo "SQL Script: /opt/lampp/htdocs/mono-v2/database/create_gabe_database.sql"
echo ""
