#!/bin/bash

# Database Export Script for KSP System
# This script exports the current database state

echo "🗄️  KSP Database Export Script"
echo "================================"

# Database configuration
DB_NAME="ksp_lamgabejaya_v2"
DB_USER="root"
DB_PASS=""
DB_HOST="localhost"
XAMPP_MYSQL="/opt/lampp/bin/mysql"
XAMPP_MYSQLDUMP="/opt/lampp/bin/mysqldump"

# Output file
OUTPUT_DIR="/opt/lampp/htdocs/mono-v2/database"
OUTPUT_FILE="$OUTPUT_DIR/ksp_lamgabejaya_v2_updated.sql"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
BACKUP_FILE="$OUTPUT_DIR/ksp_lamgabejaya_v2_backup_$TIMESTAMP.sql"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

echo "📋 Database Configuration:"
echo "   Database: $DB_NAME"
echo "   Host: $DB_HOST"
echo "   User: $DB_USER"
echo "   Output: $OUTPUT_FILE"

# Check if XAMPP MySQL is running
echo ""
echo "🔍 Checking XAMPP MySQL status..."

if ! pgrep -f "mysqld" > /dev/null; then
    echo "❌ MySQL is not running. Starting XAMPP MySQL..."
    /opt/lampp/lampp start mysql
    
    # Wait for MySQL to start
    sleep 5
    
    if ! pgrep -f "mysqld" > /dev/null; then
        echo "❌ Failed to start MySQL. Please start XAMPP manually."
        exit 1
    fi
fi

echo "✅ MySQL is running"

# Test database connection
echo ""
echo "🔍 Testing database connection..."

if $XAMPP_MYSQL -u $DB_USER -e "USE $DB_NAME;" 2>/dev/null; then
    echo "✅ Database connection successful"
else
    echo "❌ Database connection failed"
    echo "💡 Please check your database configuration"
    exit 1
fi

# Export database structure and data
echo ""
echo "📤 Exporting database..."

# Create backup first
echo "📋 Creating backup..."
$XAMPP_MYSQLDUMP -u $DB_USER --single-transaction --routines --triggers "$DB_NAME" > "$BACKUP_FILE" 2>/dev/null

if [ $? -eq 0 ]; then
    echo "✅ Backup created: $BACKUP_FILE"
else
    echo "⚠️  Backup failed, continuing with export..."
fi

# Export main database
echo "📋 Exporting main database..."
$XAMPP_MYSQLDUMP -u $DB_USER --single-transaction --routines --triggers --skip-lock-tables "$DB_NAME" > "$OUTPUT_FILE" 2>/dev/null

if [ $? -eq 0 ]; then
    echo "✅ Database exported successfully"
    echo "📁 File saved: $OUTPUT_FILE"
    
    # Show file size
    FILE_SIZE=$(du -h "$OUTPUT_FILE" | cut -f1)
    echo "📊 File size: $FILE_SIZE"
    
    # Show table count
    TABLE_COUNT=$($XAMPP_MYSQL -u $DB_USER -e "USE $DB_NAME; SHOW TABLES;" | wc -l)
    echo "📊 Tables exported: $((TABLE_COUNT - 1))"
    
else
    echo "❌ Database export failed"
    exit 1
fi

# Create database info file
echo ""
echo "📋 Creating database info..."
INFO_FILE="$OUTPUT_DIR/database_info.txt"

cat > "$INFO_FILE" << EOF
KSP Lam Gabe Jaya Database Information
=====================================

Export Date: $(date)
Export File: ksp_lamgabejaya_v2_updated.sql
Backup File: ksp_lamgabejaya_v2_backup_$TIMESTAMP.sql

Database Details:
- Name: $DB_NAME
- Host: $DB_HOST
- User: $DB_USER
- Character Set: UTF8
- Collation: utf8_general_ci

Tables: $((TABLE_COUNT - 1))
File Size: $FILE_SIZE

Export Options:
- Single Transaction: YES
- Routines: YES
- Triggers: YES
- Lock Tables: NO (to avoid locking issues)

Notes:
- This export includes both structure and data
- Backup file is created for safety
- Use this file for database restoration or setup

To restore database:
1. Create database: CREATE DATABASE $DB_NAME;
2. Import data: mysql -u $DB_USER $DB_NAME < $OUTPUT_FILE

Generated by: KSP Database Export Script
Version: 1.0
EOF

echo "✅ Database info created: $INFO_FILE"

echo ""
echo "🎉 Database export completed successfully!"
echo ""
echo "📁 Files created:"
echo "   - Main export: $OUTPUT_FILE"
echo "   - Backup file: $BACKUP_FILE"
echo "   - Info file: $INFO_FILE"
echo ""
echo "💡 You can now use these files for GitHub synchronization"
